third:
    resource: "@ThirdBundle/Controller"
    prefix:   /
    type: annotation

second:
    resource: "@SecondBundle/Resources/config/routing.yml"
    prefix:   /

first:
    resource: "@FirstBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin