wsp_firstbundle:
    resource: "@FirstBundle"
    type: annotation
    prefix: /{_locale}/
    requirements: { _locale: en|ru }

wsp_firstbundle_redirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true

login:
    path: /{_locale}/login
    defaults: { _controller: FirstBundle:Security:login, _locale: en }
    requirements:
        _locale: en|ru

login_check:
    path: /login_check

logout:
    path: /logout
